#### NumPy nedir?

- Numerical Python kelimelerinden gelir.

- Python’da bilimsel hesaplama ve sayısal veri işleme için kullanılan temel kütüphanedir.

- Büyük, çok boyutlu diziler (arrays) ve matrislerle çalışmayı kolaylaştırır.

#### Ne işe yarar?

- Çok boyutlu diziler (array) oluşturma ve yönetme

- Python listelerinden çok daha hızlıdır.

- Örn: 1000x1000 boyutunda bir matris üzerinde işlem yapabilirsin.

#### Matematiksel işlemler

- Toplama, çıkarma, çarpma, bölme

- Trigonometri, logaritma, istatistiksel hesaplamalar

#### Lineer cebir işlemleri

Matris çarpımı, tersini alma, determinant

- Yapay zekâ, makine öğrenmesi, görüntü işleme gibi alanlarda çok kritik

#### Rastgele sayı üretimi

- Simülasyonlar, istatistiksel modelleme, veri üretme

In [4]:
!pip install numpy

In [3]:
import numpy as np

##create array using numpy
## create 1D array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [8]:
arr2 = np.array([1,2,3,4,5])
print(arr2.reshape(1,5)) ## 1 row 5 column
print('*' * 20)
print(arr2.reshape(5,1)) ## 5 row 1 cloumn

[[1 2 3 4 5]]
********************
[[1]
 [2]
 [3]
 [4]
 [5]]


In [9]:
arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [ ]:
## 2d array
arr2 = np.array([[1,2,3,4,5],[4,5,6,7,8]])
print(arr2.shape)
print(arr2)

(2, 5)
[[1 2 3 4 5]
 [4 5 6 7 8]]


In [ ]:
np.arange(0,10,2) ## 2 şer artarak 0'dan 10'a kadar

array([0, 2, 4, 6, 8])

In [16]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
np.ones((3,4)) ## 3 rows 4 column 1 değerli matris

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.array([1.] * 12).reshape((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
arr = np.array([[1,2,3], [4,5,6]], dtype=np.int32)
print("Array :", arr)
print("Shape :", arr.shape)
print("Number of dimentsions : " , arr.ndim) ## array boyutu
print("Size (number of elements) : " , arr.size)
print("Data type :", arr.dtype)
print("Item size (in bytes) :", arr.itemsize)
## arr.itemsize

## Array içindeki tek bir elemanın bellekte kapladığı alanı (byte cinsinden) verir.

## Örneğin dtype=np.int32 ise her eleman 4 byte kaplar.

## dtype=np.float64 olsaydı her eleman 8 byte olurdu.
## Yani itemsize, 1 elemanın boyutu.

Array : [[1 2 3]
 [4 5 6]]
Shape : (2, 3)
Number of dimentsions :  2
Size (number of elements) :  6
Data type : int32
Item size (in bytes) : 4


In [ ]:
### Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element Wise addition
print("Addition:", arr1+arr2)

## Element Wise Substraction
print("Substraction:", arr1-arr2)

# Element-wise multiplication
print("Multiplication:", arr1 * arr2)

# Element-wise division
print("Division:", arr1 / arr2)

In [ ]:
import numpy as np

arr = np.array([2,3,4,5,6])

## square root (karekök alma)
print(np.sqrt(arr))  

## Exponential (e^x hesaplama)
print(np.exp(arr))   

## Sine (sinüs hesaplama, radyan cinsinden)
print(np.sin(arr))   

## natural log (doğal logaritma, ln(x))
print(np.log(arr))   

In [35]:
##array slicing and Indexing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [36]:
print(arr[0][-1])

4


In [ ]:
print(arr[1:])

[[ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
## arr dizisindeki 7,8,11,12'yi al
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [ ]:
## 3,4,7,8 al

print(arr)
arr[0:2,2:]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[3, 4],
       [7, 8]])

In [ ]:
## 6,7,10,11'i al
arr[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [49]:
## Modify Array elements
arr[0,0] = 100
arr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [52]:
##array'in 1. satırından itibaren gelen satırlarından tüm sütunlarını 1 yap
arr[1:] = 400
arr

array([[100,   2,   3,   4],
       [400, 400, 400, 400],
       [400, 400, 400, 400]])

In [ ]:
### statistical concepts--Normalization
##to have a mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
print("Mean:",mean)

std_dev = np.std(data)
print("Std:",std_dev)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)


Mean: 3.0
Std: 1.4142135623730951
Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)



In [54]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])

🔹 Normalization (genel anlamda)

Verileri belirli bir ölçeğe getirme işlemidir.

Amaç: farklı büyüklüklerdeki verileri karşılaştırılabilir hale getirmek.

Örneğin, bir veri setinde yaş (0–100) ve maaş (0–100.000) varsa, maaş çok büyük olduğu için öğrenmede baskın çıkar. Normalization yapınca ikisini benzer ölçeğe getirirsin.

    (veri - ort) / standart sapma